# ============== APPLICATION NAME =========================

spring.application.name=SpringBoot-JPA


# ============================================================
# POSTGRESQL DATABASE CONFIGURATION
# ============================================================

# JDBC URL (Format: jdbc:postgresql://HOST:PORT/DATABASE_NAME)

spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_jpa

# PostgreSQL username
spring.datasource.username=postgres
# PostgreSQL password
spring.datasource.password=U$@ID12345
# PostgreSQL JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver


# ============================================================
# HIBERNATE / JPA CONFIGURATION
# ============================================================

# Automatically create/update database schema
#
# create       -> Drops old tables and creates new tables every startup
# create-drop  -> Same as create, but drops tables when app stops
# update       -> Updates schema without deleting existing data
# validate     -> Validates schema only
# none         -> Hibernate does nothing
#
# For learning:
spring.jpa.hibernate.ddl-auto=update

# Show generated SQL queries in console
spring.jpa.show-sql=true

# Format SQL nicely in console output
spring.jpa.properties.hibernate.format_sql=true

# Adds SQL comments generated by Hibernate
spring.jpa.properties.hibernate.use_sql_comments=true

# PostgreSQL dialect
# Hibernate usually detects automatically in Spring Boot 3+
# Can be omitted, but keeping it helps understanding
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ============================================================
# LOGGING (VERY IMPORTANT FOR LEARNING JPA)
# ============================================================

# Show SQL queries executed by Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Show query parameter values
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# ============================================================
# SPRING BOOT DEVTOOLS
# ============================================================

# Auto restart application on code changes
spring.devtools.restart.enabled=true


# ============================================================
# OPTIONAL: SERVER CONFIGURATION
# ============================================================

# Application port
server.port=8080



